### ISSUE TITLE
Broken redis pod SecurityContext configuration

### ISSUE THREAD

**Issue by excavador** [spotahome/redis-operator#159]
### Expected behaviour

RedisFailover with persistent storage created by operator works correctly

### Actual behaviour

pods created by RedisFailover with persistent storage do not have permission to write to disk according to broken configuration of SecurityContext.

docker hub redis image create separate user 'redis' with uid 100 and gid 101
default SecurityContext uid is 1000, gid is 1000

### Steps to reproduce the behaviour

Create RedisFailover with persistent storage in AWS EKS cluster

### Environment

How are the pieces configured?
* Redis Operator version: https://github.com/spotahome/redis-operator/commit/df4c0301d5ca0b88f2e9bd5d0bd6586512675981
* Kubernetes version: 1.12.7
`
                "nodeInfo": {
                   ...
                    "kernelVersion": "4.14.106-97.85.amzn2.x86_64",
                    "osImage": "Amazon Linux 2",
                    "containerRuntimeVersion": "docker://18.6.1",
                    "kubeletVersion": "v1.12.7",
                    "kubeProxyVersion": "v1.12.7",
                    "operatingSystem": "linux",
                    "architecture": "amd64"
                },
`
* RBAC active (by default in EKS)

### Logs

api response
`MISCONF Redis is configured to save RDB snapshots, but it is currently not able to persist on disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.`

redis logs
`
1:M 15 May 11:06:31.917 * Starting BGSAVE for SYNC with target: disk
1:M 15 May 11:06:31.917 * Background saving started by pid 83
83:C 15 May 11:06:31.917 # Failed opening the RDB file dump.rdb (in server root dir /data) for saving: Permission denied
1:M 15 May 11:06:31.974 # Background saving error
1:M 15 May 11:06:31.974 # Connection with slave 10.0.92.200:6379 lost.
1:M 15 May 11:06:31.974 # SYNC failed. BGSAVE child returned an error
`
exec inside pod
`
/data $ mount | grep data
/dev/nvme2n1 on /data type ext4 (rw,relatime,debug,data=ordered)
/data $ touch /data/test
touch: /data/test: Permission denied
/data $ whoami
whoami: unknown uid 1000
`

**Comment by excavador** [comment]
my workaround for this problem:
```
   redis:
+    securityContext:
+      runAsUser:  100
+      runAsGroup: 101
+      fsGroup:    0
     storage:
       persistentVolumeClaim:
```

**Comment by h3yduck** [comment]
+1, i'm using:
```yaml
securityContext:
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000
```

**Comment by loginvarun** [comment]
In our On-Prem Kubernetes cluster with PSP enabled, we also faced same issue and find out that 
Mount point "/data" is owned by root:root with permission 755, while using external PVC.

As a workaround, We customized our redisfailover deployment chart to use securitycontext as part of its deployment:
Fix:
```
securityContext:
  runAsUser: 1000
  runAsGroup: 1000
  runAsNonRoot: true
  fsGroup: 1000
```

With this change, "/data" filesystem is now owned by root:redis. Redis server got the write permission  on its data directory.
```
/data $ ls -ld /data
drwxrwsr-x    3 root     redis         4096 Sep 17 14:31 /data
```

**Comment by bbobrov** [comment]
i would say that the default `securityContext` is not correct - https://github.com/spotahome/redis-operator/blob/master/operator/redisfailover/service/generator.go#L639 . The operator uses redis v5 with image for alpine, and in that image uid is 999 and gid is 1000 (https://github.com/docker-library/redis/blob/master/5.0/alpine/Dockerfile) and user with uid 1000, set by the operator, does not exist. It kind of works, because in the alpine image `/data` has permissions 777 and even non-existent user can write there.

It becomes worse with non-default redis image, because, for example, in the redis image that i use, `/data` is not 777 and redis with persistent volume fails.

The issue was introduced in https://github.com/spotahome/redis-operator/pull/148

I propose to remove the default `securityContext` or make it the default configurable on `helm install` (with the ability to override it on `kubectl create`).
