### ISSUE TITLE
Problem with mismatching types in the client-go library

### ISSUE THREAD

**Issue by Kyrremann** [spotahome/redis-operator#33]
Hi again
New day, new problem.

I'm trying to expand our Go-Api with the Redis Api, but I'm having trouble creating the Redis client which allows me to create the new RedisFailover. The issues seems like a mismatching import. Where I use a type `Config`, your code expectes `redis.Config` as the type. And I can't understand where I'm supposed to get the correct type from.

My imports are:
```
redisapi "github.com/spotahome/redis-operator/api/redisfailover/v1alpha2"
redisclient "github.com/spotahome/redis-operator/client/k8s/clientset/versioned/typed/redisfailover/v1alpha2"
"k8s.io/client-go/rest"
```

And the following line:
```
config, _ := rest.InClusterConfig()
client, _ := redisclient.NewForConfig(config)
```

Gives me this error:
```
Cannot use 'config' (type "github.com/nais/naisd/vendor/k8s.io/client-go/rest".*Config) as type "github.com/spotahome/redis-operator/vendor/k8s.io/client-go/rest".*rest.Config
```

This also happens for this line:
```
redisclient.RedisFailoversGetter(client).RedisFailovers(namespace).Create(failover)
```

```
Cannot use 'failover' (type "github.com/nais/naisd/vendor/github.com/spotahome/redis-operator/api/redisfailover/v1alpha2".*RedisFailover) as type "github.com/spotahome/redis-operator/api/redisfailover/v1alpha2".*v1alpha2.RedisFailover
```

Am I messing up my imports, or is there something I havn't understood about Go and libraries?

Thanks for the help!

**Comment by slok** [comment]
Hi @Kyrremann Kyrremann

The main problem is that you are not getting the dependencies correctly, mainly kubernetes deps, that's why Go will try to use the ones vendored with the Redis failover, and throw the conflicts that you wrote on the issue.

[Here](https://github.com/slok/redis-operator-as-dependency) you have a working example of how you would use these dependencies, the example lists your redis failovers using redis-failover client.

Hope it helps :)

Best.

**Comment by Kyrremann** [comment]
Thanks for the help. Turns out the problem was a lot easier to fix. It was just Intellij who reported wrong errors. Which is kinda embarrassing on my side, as I didn't think of that.
