### ISSUE TITLE
Operator continuously updates Kubernetes deployments

### ISSUE THREAD

**Issue by avthart** [spotahome/redis-operator#580]
We are using Kyverno which validates every object on change. 

The redis-operator is updating the rfs deployments overy 30 seconds, even when nothing is changed. 
This creates additional load on Kyverno, especially in environments with a lot of redisfailovers instances. 

This can be verified with:

```bash
kubectl get deploy -w
```

Or check the number `observedGeneration` which is in our case 496690

It would be great if the rfs deployments would be updated only when needed. 

Also see https://github.com/spotahome/redis-operator/issues/410#issuecomment-1276374527

**Comment by avthart** [comment]
Did a diff on two versions:

```
diff /tmp/1.yaml /tmp/2.yaml 
7c7
<   generation: 496690
---
>   generation: 496693
23c23
<   resourceVersion: "1087217544"
---
>   resourceVersion: "1087219466"
180c180
<   observedGeneration: 496690
---
>   observedGeneration: 496693
```

**Comment by nickvth** [comment]
+1

**Comment by raghu-nandan-bs** [comment]
@samof76 to address this, I can think of couple of improvements.
- using cached informers instead of making direct "get" calls to kubernetes API [like here](https://github.com/spotahome/redis-operator/blob/fe8090ac7291ee53ac30e534fa1cc03e5759fd10/service/k8s/statefulset.go#L53)
- use a "hash" of redisfailover object as annotation, and *apply* the changes whenever this "hash" changes due to CR updates. This way, we dont have to call *create* / *apply* call every thirty seconds like [here](https://github.com/spotahome/redis-operator/blob/fe8090ac7291ee53ac30e534fa1cc03e5759fd10/operator/redisfailover/service/client.go#L102), but only when this resource hash changes.
what are your thoughts on this?

**Comment by avthart** [comment]
Please re-open ticket. This is still an issue.

**Comment by avthart** [comment]
Not stale. Reopen ticket.
