### ISSUE TITLE
[Question] Only use sentinel configuration possible?

### ISSUE THREAD

**Issue by h0jeZvgoxFepBQ2C** [spotahome/redis-operator#614]
### Expected behaviour

Don't run a redis cluster in "cluster mode"; but only in sentinel mode. 
We are using sidekiq and the documentation mentions following: https://github.com/sidekiq/sidekiq/wiki/Using-Redis#architecture

>  Cluster is NOT appropriate for Sidekiq as Sidekiq has a few very hot keys which are constantly changing (aka queues) and Cluster cannot guarantee high-performance transactions, necessary to keep your job system fast and consistent. 

So we would like to use only sentinel mode, but are not sure if this operator allows this / configures correctly.

### Actual behaviour

Not sure if possible. would be good to document this.

### Steps to reproduce the behaviour

Setting 

```yaml
sentinel:
  replicas: 3

redis:
  replicas: 1
```

I can create a PR to improve the documentation to clarify if this is no problem to do! 
Thank you for your great work! ❤️

**Comment by dcoxall** [comment]
I think this is just a mis-understanding. Sentinel is a separate process/container/service that monitors a standalone redis setup. A traditional redis setup is 1 leader and multiple followers/replicas. The issue with this setup is that the leader isn't redundant if it fails. This is where sentinel gets involved. Sentinel _wraps_ this redis setup and will issue the relevant commands to a follower to promote it to a leader if the current leader fails.

So that means you need redis nodes and sentinel nodes.

The `sentinel.replicas` indicates the desired number of sentinel nodes whilst `redis.replicas` indicated the desired number of traditional redis nodes. The sentinel nodes do not handle the typical key value redis work.
