### ISSUE TITLE
Master election

### ISSUE THREAD

**Issue by normander** [spotahome/redis-operator#62]
Is there any kind of method to speed up election of master after failed present master?

**Comment by jchanam** [comment]
Hi @normander,

The failover procedure is managed by Sentinel. You can change the configuration with a configmap, setting this values.

I recommend you to check the [Sentinel Documentation](https://redis.io/topics/sentinel) to decide how exactly to configure it.

Keep in mind that in order to get the Sentinels working, they have to monitor themselves at start and that the group has to be called `mymaster` (the operator will change the monitoring with the Redis master when healed).

Configuration by default:
```
sentinel monitor mymaster 127.0.0.1 6379 2
sentinel down-after-milliseconds mymaster 1000
sentinel failover-timeout mymaster 3000
sentinel parallel-syncs mymaster 2
```

**Comment by kmcrawford** [comment]
I was having the same issue.  Due to autoscaling, or cluster upgrades the master can and will be terminated. In pr #70 I added a shutdown hook that will elect a new master if a master is being shutdown.
