### ISSUE TITLE
redis auth?

### ISSUE THREAD

**Issue by mzupan** [spotahome/redis-operator#66]
Is there a way to setup redis with auth and have sentinel use that auth to connect?

**Comment by jchanam** [comment]
Hi @marcemq,

We are not currently working implementing this enhancement. If you want to give it a try, I'll be happy to assist if necessary.

**Comment by marcemq** [comment]
Hi @jchanam,

I'll give it a try then and contact you too.

**Comment by marcemq** [comment]
So, I’ve spent some time reading the code and I came up with two ways to approach this.

1. Generate the `reds.conf` file with the `requirepass <password>` argument at [operator/redisfailover/service/generator.go](https://github.com/spotahome/redis-operator/blob/master/operator/redisfailover/service/generator.go#L122)  which is going to impact all `redis-cli` command execution by the operator since those are going to require to use the `-a <password>` option. Also: 
	* Can the value of `<password>` be added as new entry of `RedisFailover`?
	* `rediscli.Options` needs to have access to the value of `<password>` too right? So it can be set to the `Password` [entry](https://github.com/spotahome/redis-operator/blob/master/service/redis/client.go#L121).
	* If we follow this approach, security needs to be consider too, do you have a recommendation to handle this? I was thinking on having  `<password>` as an entry in the yaml file to be deploy but this is a potential security risk.

2. Using `redis-cli` on _execution time_ by setting `requirepass` argument like this:
```
$ kubectl exec -it rfs-<NAME> -- redis-cli -h <hostname> -p <port> CONFIG get requirepass
1) "requirepass"
2) ""
$ kubectl exec -it rfs-<NAME> -- redis-cli -h <hostname> -p <port> CONFIG set requirepass 'mypass'
OK
$ kubectl exec -it rfs-<NAME> -- redis-cli -h <hostname> -p <port> CONFIG get requirepass
(error) NOAUTH Authentication required.
$ kubectl exec -it rfs-<NAME> -- redis-cli -h <hostname> -p <port> -a mypass CONFIG get requirepass
1) "requirepass"
2) "mypass"
```

So, can we use the second approach? If don't can we meet and work to define the minimum authentication architecture?

**Comment by ihrankouski** [comment]
@marcemq It would be super cool if RedisFailover could take the password value from k8s secret, in the same manner as env vars do:
```
apiVersion: storage.spotahome.com/v1alpha2
kind: RedisFailover
spec:
  ...
  password:
    valueFrom:
      secretKeyRef:
         name: <SECRET-NAME>
         key: <PASSWORD-Key>
```

And somebody who does not care about security so much could alternatively specify the password as plain string right in the yaml:
```
  password: mysuperpass111
```

**Comment by jchanam** [comment]
I think that, as the password is something that should be cross known, it should be a configuration in the Redis spec. As @ihrankouski is saying, we can allow to have directly a secret reference so we don't have in clear the password.

There is a question to be made:
- What happens if we change the password? Do we want to reload the redis/sentinels? Do we want to do it on the fly? What about the possible service disruption if the password is changed?

**Comment by marcemq** [comment]
@ihrankouski and @jchanam thanks for the guidance. I'll review more in detail about k8s secrets.

And looking into a different authentications mechanisms (i.e: MariaDB, wordpress) can help us to define a robust authentication architecture.

**Comment by mrgavinconway001** [comment]
If anyone is moving this forward I'd be very interested to try it out for them.

**Comment by marcemq** [comment]
Hi @mrgavinconway001,

at the moment no, I had to stop due to other duties, do you want to be the owner of this?

**Comment by mrgavinconway001** [comment]
> Hi @mrgavinconway001,
> 
> at the moment no, I had to stop due to other duties, do you want to be the owner of this?

I'm no go coder so whilst I could test it I couldn't write it.
